-- MySQL Script generated by MySQL Workbench
-- sex 02 abr 2021 23:11:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mktwar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mktwar` ;

-- -----------------------------------------------------
-- Schema mktwar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mktwar` ;
USE `mktwar` ;

-- -----------------------------------------------------
-- Table `mktwar`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mktwar`.`player` ;

CREATE TABLE IF NOT EXISTS `mktwar`.`player` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(90) NULL,
  `player_username` VARCHAR(90) NULL,
  `player_password` VARCHAR(256) NULL,
  `player_trophies` INT NULL,
  `player_avatar` INT NULL,
  `player_coins` INT NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `player_username_UNIQUE` (`player_username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mktwar`.`player_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mktwar`.`player_stats` ;

CREATE TABLE IF NOT EXISTS `mktwar`.`player_stats` (
  `stats_player_id` INT NOT NULL AUTO_INCREMENT,
  `stats_total_games` INT NULL,
  `stats_max_trophies` INT NULL,
  `stats_total_losses` INT NULL,
  `stats_total_wins` INT NULL,
  PRIMARY KEY (`stats_player_id`),
  CONSTRAINT `fk_player_stats_id`
    FOREIGN KEY (`stats_player_id`)
    REFERENCES `mktwar`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mktwar`.`player_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mktwar`.`player_settings` ;

CREATE TABLE IF NOT EXISTS `mktwar`.`player_settings` (
  `sett_player_id` INT NOT NULL,
  `sett_sound_on` TINYINT NULL,
  PRIMARY KEY (`sett_player_id`),
  CONSTRAINT `fk_player_settings_id`
    FOREIGN KEY (`sett_player_id`)
    REFERENCES `mktwar`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
